socialcomments/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('socialcomments.views',
	url(r'^form/$', 'form', name = 'socialcomments_ajax_form'),
	url(r'^connect/$', 'connect', name = 'socialcomments_connect'),
	url(r'^disconnect/$', 'disconnect', name = 'socialcomments_disconnect'),
	url(r'^connect/callback/$', 'callback', name = 'socialcomments_callback'),
)

socialcomments/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.conf import settings
from django.utils.importlib import import_module
from socialcomments.managers import *
from socialcomments.helpers import get_provider_choices

if 'bambu.notifications' in settings.INSTALLED_APPS:
	from bambu import notifications
else:
	from bambu.mail.shortcuts import render_to_mail

MARKDOWN = getattr(settings, 'COMMENTS_MARKDOWN', True)

class Comment(models.Model):
	name = models.CharField(max_length = 50)
	website = models.URLField(max_length = 255, null = True, blank = True)
	provider = models.CharField(max_length = 100, db_index = True, choices = get_provider_choices())
	identity = models.CharField(max_length = 255, db_index = True)
	sent = models.DateTimeField(auto_now_add = True, db_index = True)
	approved = models.BooleanField(default = False, db_index = True)
	spam = models.BooleanField(default = False, db_index = True)
	body = models.TextField()
	content_type = models.ForeignKey(ContentType)
	object_id = models.PositiveIntegerField(db_index = True)
	content_object = generic.GenericForeignKey()
	objects = CommentManager()
	
	def __unicode__(self):
		return u'Re: %s' % unicode(self.content_object)
	
	def get_absolute_url(self):
		return self.content_object.get_absolute_url() + '#comment-%d' % self.pk
	
	def get_provider(self):
		if not getattr(self, '_provider', None):
			module, dot, klass = self.provider.rpartition('.')
			module = import_module(module)
			self._provider = getattr(module, klass)
		
		return self._provider
	
	def get_avatar(self, size = 50):
		provider = self.get_provider()
		return provider().get_avatar(self.identity, size)
	
	@property
	def icon(self):
		provider = self.get_provider()
		return provider.icon
	
	def check_for_spam(self, request):
		provider = self.get_provider()
		return provider().check_for_spam(self, request)
	
	def check_for_approval(self):
		provider = self.get_provider()
		return provider().check_for_approval(self)
	
	def post_to_profile(self):
		provider = self.get_provider()
		return provider().post(self)
	
	def sanitise(self, markdown = False):
		provider = self.get_provider()
		self.body = provider().sanitise(self.body, markdown)
	
	def save(self, *args, **kwargs):
		notify = kwargs.pop('notify', True)
		
		if self.spam:
			self.approved = False
		
		new = not self.pk and not self.spam
		if new and not self.approved and not self.spam:
			self.approved = self.check_for_approval()
		
		super(Comment, self).save(*args, **kwargs)
		
		if new and notify:
			if not 'bambu.notifications' in settings.INSTALLED_APPS:
				render_to_mail(
					u'New comment submitted',
					'socialcomments/mail.txt',
					{
						'comment': self,
						'author': self.content_object.author
					},
					self.content_object.author
				)
			else:
				notifications.notify('socialcomments.comment_posted',
					self.content_object.author,
					comment = self,
					actions = [
						{
							'urlname': 'admin:comments_comment_change',
							'args': [self.pk],
							'title': 'View the comment'
						}
					]
				)
	
	class Meta:
		ordering = ('-sent',)
		get_latest_by = 'sent'
	
	class QuerySet(models.query.QuerySet):
		def live(self):
			return self.filter(
				approved = True,
				spam = False
			)

socialcomments/forms.py
from django import forms
from django.conf import settings
from django.utils.importlib import import_module
from socialcomments.models import Comment

class CommentForm(forms.ModelForm):
	provider = forms.CharField(
		widget = forms.HiddenInput
	)
	
	identity = forms.CharField(
		widget = forms.HiddenInput
	)
	
	def __init__(self, *args, **kwargs):
		super(CommentForm, self).__init__(*args, **kwargs)
		self.fields['body'].label = u'Your comment'
	
	def save(self, commit = True):
		obj = super(CommentForm, self).save(commit = False)
		obj.provider = self.cleaned_data.get('provider')
		obj.sanitise()
		
		if commit:
			obj.save()
		
		return obj
	
	class Meta:
		model = Comment
		fields = ('name', 'website', 'identity', 'body',)

class OAuthCommentForm(CommentForm):
	name = forms.CharField(
		widget = forms.HiddenInput
	)
	
	website = forms.CharField(
		widget = forms.HiddenInput
	)

socialcomments/views.py
from socialcomments import PROVIDERS
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.importlib import import_module
from django.template.response import TemplateResponse
from django.contrib.contenttypes.models import ContentType
from django.views.decorators.cache import never_cache
from django.contrib import messages

@never_cache
def form(request):
	provider = request.method == 'POST' and request.POST.get('provider') or request.GET.get('p')
	if not provider in PROVIDERS:
		return HttpResponse('')
	
	module, dot, klass = provider.rpartition('.')
	remainder, dot, submodule = module.rpartition('.')
	module = import_module(module)
	klass = getattr(module, klass)
	obj = klass()
	connected = False
	
	initial = {
		'provider': provider
	}
	
	identity = None	
	if request.session.get('socialcomments.provider.name') == provider:
		identity = request.session.get('socialcomments.provider.identity')
		if identity:
			initial['identity'] = identity['id']
			initial['name'] = identity['display_name']
			initial['website'] = identity['url']
			connected = True
	
	form = obj.get_form(request.POST or None, initial = initial)
	if request.method == 'POST' and form.is_valid():
		if form.cleaned_data.get('post'):
			content_type = ContentType.objects.get(
				pk = request.POST.get('content_type')
			)
			
			content_object = content_type.get_object_for_this_type(
				pk = request.POST.get('object_id')
			)
			
			obj.post(
				content_object,
				request.session['socialcomments.provider.access_token']
			)
		
		return HttpResponse('::OK::')
	
	templates = [
		'socialcomments/form/%s.inc.html' % submodule,
		obj.template
	]
	
	if identity:
		avatar = obj.get_avatar(identity['id'], 16)
	else:
		avatar = None
	
	return TemplateResponse(
		request,
		templates,
		{
			'form': form,
			'provider_name': provider,
			'provider_name_verbose': obj.verbose_name,
			'connected': connected,
			'identity': identity,
			'avatar': avatar
		}
	)

@never_cache
def connect(request):
	provider = request.GET.get('p')
	if not provider in PROVIDERS:
		return HttpResponse('')
	
	module, dot, klass = provider.rpartition('.')
	remainder, dot, submodule = module.rpartition('.')
	module = import_module(module)
	klass = getattr(module, klass)
	obj = klass()
	
	request.session['socialcomments.provider.referer'] = request.META.get('HTTP_REFERER')
	request.session.modified = True
	return obj.connect()

@never_cache
def callback(request):
	provider = request.GET.get('p')
	if not provider in PROVIDERS:
		return HttpResponse('')
	
	module, dot, klass = provider.rpartition('.')
	remainder, dot, submodule = module.rpartition('.')
	module = import_module(module)
	klass = getattr(module, klass)
	obj = klass()
	
	kwargs = {}
	for key, value in request.GET.items():
		if value:
			kwargs[key] = value
	
	referer = request.session.pop('socialcomments.provider.referer', '/')
	
	try:
		details = obj.finalise_connection(**kwargs)
	except:
		messages.error(request, u'It wasn\'t possible to authenticate you.')
		return HttpResponseRedirect(referer + '#comments')
	
	if not 'access_token' in details and not 'oauth_token' in details:
		raise Exception(details)
		messages.error(request, u'It wasn\'t possible to authenticate you.')
		return HttpResponseRedirect(referer + '#comments')
	
	info = obj.get_identity(details)
	request.session['socialcomments.provider.name'] = provider
	
	request.session['socialcomments.provider.access_token'] = details
	request.session['socialcomments.provider.identity'] = info
	
	request.session.modified = True
	return HttpResponseRedirect(referer + '#comments')

@never_cache
def disconnect(request):
	referer = request.META.get('HTTP_REFERER', '/')
	request.session.pop('socialcomments.provider.referer', None)
	request.session.pop('socialcomments.provider.name', None)
	request.session.pop('socialcomments.provider.access_token', None)
	request.session.pop('socialcomments.provider.identity', None)
	request.session.modified = True
	
	return HttpResponseRedirect(referer + '#comments')

socialcomments/templates/socialcomments/comment.inc.html
{% load markup comments icons %}

<article class="row comment">
	<div class="span1 avatar-container">
		<img class="avatar" src="{{ comment|gravatar }}" alt="{{ comment.name }}" />
	</div>
	
	<div class="span7" id="comment-{{ comment.pk }}">
		<h3>
			{% if comment.website %}<a href="{{ comment.website }}" target="_blank">{% endif %}
			{{ comment.name }}
			{% if comment.website %}</a>{% endif %}
			<small>
				<a href="#comment-{{ comment.pk }}">{{ comment.sent|date }}</a>
				via {% icon comment.icon %} {{ comment.get_provider_display }}
			</small>
		</h3>
		
		{{ comment.body|striptags|markdown }}
	</div>
	
	<div style="clear: both;"></div>
</article>

socialcomments/templates/socialcomments/form.inc.html
{% load icons comments %}
{% load url from future %}

{% include 'socialcomments/tabs.inc.html' %}

<form action="{{ comment_form_action|default:'comment/' }}#comment-form" method="post" class="form-horizontal">
	<div id="social-comment-form"></div>
	<div class="form-actions">
		{% csrf_token %}
		
		{% if obj %}
			<input type="hidden" name="content_type" value="{{ obj|contenttype }}" />
			<input type="hidden" name="object_id" value="{{ obj.pk }}" />
		{% endif %}
		
		<button type="submit" class="btn btn-success">{% icon 'ok' 'white' %} Submit comment</button>
		<small>Comments may require approval.</small>
	</div>
</form>

{% include 'socialcomments/script.inc.html' %}

socialcomments/templates/socialcomments/form/base.inc.html
{% if form.non_field_errors %}
	<div class="alert-message alert-error alert-block">
		{% for error in form.non_field_errors %}
		{{ error }}
		{% endfor %}
	</div>
{% endif %}

{% for field in form.visible_fields %}
	{% include 'field.inc.html' %}
{% endfor %}

{{ form.hidden_fields|join:'' }}

socialcomments/templates/socialcomments/form/connect.inc.html
{% load url from future %}
<p>
	<a class="btn btn-primary" href="{% url 'socialcomments_connect' %}?p={{ provider_name }}">Login to {{ provider_name_verbose.capitalize }}</a>
	&nbsp;to post a comment
</p>

socialcomments/templates/socialcomments/form/oauth.inc.html
{% load url from future %}

{% if form.non_field_errors %}
	<div class="alert-message alert-error alert-block">
		{% for error in form.non_field_errors %}
		{{ error }}
		{% endfor %}
	</div>
{% endif %}

<div class="control-group clearfix">
	<div class="controls">
		{% if not connected %}
			{% include 'socialcomments/form/connect.inc.html' %}
		{% else %}
			<p style="line-height: 16px;">
				{% if avatar %}
					<img src="{{ avatar }}" align="left" width="16" height="16" />&nbsp;
				{% endif %}
				
				You&rsquo;re logged in as <a href="{{ identity.url }}" target="_blank">{{ identity.display_name }}</a>.
				(<a href="{% url 'socialcomments_disconnect' %}">Log out</a>)
			</p>
		{% endif %}
	</div>
</div>

{% if not connected %}
	<script>
		$('#social-comment-form').closest('form').find('[type="submit"]').hide();
	</script>
{% else %}
	<script>
		$('#social-comment-form').closest('form').find('[type="submit"]').show();
	</script>
	
	{% for field in form.visible_fields %}
		{% include 'field.inc.html' %}
	{% endfor %}

	{{ form.hidden_fields|join:'' }}
{% endif %}

socialcomments/templates/socialcomments/form/twitter.inc.html
{% extends 'socialcomments/form/oauth.inc.html' %}

socialcomments/templates/socialcomments/list.inc.html
{% load humanize %}

<a id="comments"></a>
{% if obj.comments.live.count > 0 %}
	<hr />
	<h2>{{ obj.comments.live.count|apnumber|capfirst }} comment{{ obj.comments.live.count|pluralize }}</h2>
	
	{% for comment in obj.comments.live %}
		{% include 'socialcomments/comment.inc.html' %}
		{% if not forloop.last %}<hr />{% endif %}
	{% endfor %}
	
	{% if comment_form %}
		<hr />
		<a id="comment-form"></a>
		<h3>Post a comment</h3>
	{% endif %}
{% elif comment_form %}
	<hr />
	<a id="comment-form"></a>
	<h3>Post a comment</h3>
{% elif 'comment-sent' in request.GET %}
	<p>Thanks for your comment!</p>
{% endif %}

{% if comment_form %}
	{% include 'socialcomments/form.inc.html' with obj=obj %}
{% endif %}

socialcomments/templates/socialcomments/script.inc.html
{% load url from future %}
<script>
	function openSocialCommentForm(p) {
		$('#social-comment-form').closest('form').find('[type="submit"]').attr('disabled', 'disabled');
		
		if(typeof(p) == 'undefined') {
			try {
				p = $('#social-comment-tabs .active a').attr('href').substr(1);
			} catch (err) {
				return;
			}
		}
		
		$.ajax(
			{
				url: '{% url 'socialcomments_ajax_form' %}?p=' + p,
				dataType: 'html',
				success: function(html) {
					$('#social-comment-form').closest('form').find('[type="submit"]').removeAttr('disabled').show();
					$('#social-comment-form').html(html);
				}
			}
		);
	}
	
	jQuery(document).ready(
		function() {
			$('#social-comment-tabs a').on('click',
				function(e) {
					$('#social-comment-form').html('');
					
					e.preventDefault();
					$(this).closest('ul').find('li.active').removeClass('active');
					$(this).closest('li').addClass('active');
					
					openSocialCommentForm(
						$(this).attr('href').substr(1)
					);
				}
			);
			
			$('#social-comment-form').closest('form').on('submit',
				function(e) {
					$(this).find('[type="submit"]').attr('disabled', 'disabled');
					
					if($(this).data('validated')) {
						return;
					}
					
					e.preventDefault();
					if($(this).data('submitting')) {
						return;
					}
					
					$(this).data('submitting', true);
					
					$.ajax(
						{
							type: 'POST',
							url: '{% url 'socialcomments_ajax_form' %}',
							data: $(this).serialize(),
							context: $(this),
							success: function(data) {
								if(data == '::OK::') {
									$(this).data('validated', true).submit();
								} else {
									$('#social-comment-form').closest('form').find('[type="submit"]').removeAttr('disabled');
									$('#social-comment-form').html(data);
									
									try {
										console.log('Errors detect in form');
									} catch (err) {
										// Can't log to console
									}
								}
								
								$(this).data('submitting', false);
							}
						}
					);
				}
			);
			
			openSocialCommentForm();
		}
	);
</script>

socialcomments/templates/socialcomments/tabs.inc.html
{% load icons %}
<ul id="social-comment-tabs" class="nav nav-pills">
	{% for provider in social_comment_providers %}
		<li{% if provider.active %} class="active"{% endif %}>
			<a href="#{{ provider.name }}">{% icon provider.icon %} {{ provider.verbose_name.capitalize }}</a>
		</li>
	{% endfor %}
</ul>